### ISSUE TITLE
Does not work with CocoaLumberjack 2 (XCode 6) 

### ISSUE THREAD

**Issue by RomainBoulay** [robbiehanson/XcodeColors#22]
I followed the README in both repositories (yours and CocoaLumberjack), but I can't get colors in the XCode terminal.

Is that known? Or is there a fix or workaround I can use?

Thanks!

**Comment by inteist** [comment]
How did you fix it? It does not seem to be working for me.

**Comment by rismay** [comment]
Same here.

**Comment by RomainBoulay** [comment]
![screen shot 2015-03-04 at 19 51 37](https://cloud.githubusercontent.com/assets/169323/6490620/fc36531a-c2a7-11e4-94c2-96f7325a7621.png)
