### ISSUE TITLE
Does not work with iOS and Xcode Version 6.1.1 (6A2008a)

### ISSUE THREAD

**Issue by Koranda** [robbiehanson/XcodeColors#25]
I tested the plugin in iOS project and console colors does not work. TestXcodeColors works well.

When I set environment variables programmatically or through edit scheme, colors still does not work. 

Plugin is instaled in "~/Library/Application Support/Developer/Shared/Xcode/Plug-ins/XcodeColors.xcplugin". 

I used NSLog and ESCAPE sequences from TestXcodeColors.

**Comment by wangjiajia0822** [comment]
https://github.com/CocoaLumberjack/CocoaLumberjack/blob/master/Documentation/XcodeColors.md

**Comment by Koranda** [comment]
Thanks. This solution I tested, but with ESCAPE sequence from TestXcodeColors for IOS  @"\xC2\xA0[". Now I tested with ESCAPE sequence for MAC @"\033[". All is okey.

**Comment by beuady** [comment]
the second floor is the correct. Now I see that the xcodecolors need to be config in the project envirment values. Thanks for the 'wangjiajia0822'.

**Comment by mihir-mehta** [comment]
Only Escape Sequence for Mac is working, Escape sequence for iOS Doesn't print color in console.
