### ISSUE TITLE
Not working with Xcode 6.2

### ISSUE THREAD

**Issue by mamaral** [robbiehanson/XcodeColors#32]
Upgraded my phone to iOS 8.2, which required Xcode 6.2, and it seems like XcodeColors stopped working. Any idea if there's anything I need to do to get it working again?

**Comment by clsource** [comment]
Check this

https://github.com/robbiehanson/XcodeColors/wiki/XcodeUpdates

XCode 6.2 UUID is A16FF353-8441-459E-A50C-B071F53F51B7

:+1:

**Comment by mamaral** [comment]
YES, that did it. Thanks @clsource!
