### ISSUE TITLE
XcodeColors not working on latest Xcode version (7.2)

### ISSUE THREAD

**Issue by RazvanMaris** [robbiehanson/XcodeColors#71]
After installing the new version of Xcode, I even removed and reinstalled XcodeColors but it still doesn't work.

**Comment by JaviSoto** [comment]
There's a couple PRs open about it: https://github.com/robbiehanson/XcodeColors/pull/67 and https://github.com/robbiehanson/XcodeColors/pull/70. Hopefully one of them gets merged soon!

**Comment by robbiehanson** [comment]
Pull request #70 has been merged.
